# Generated by Django 6.0.2 on 2026-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_recruiter_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
