# Generated by Django 6.0.2 on 2026-04-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_match_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
