# Generated by Django 6.0.2 on 2026-04-07 12:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_skill_name_case_insensitive'),
        ),
    ]
