# Generated by Django 6.0.2 on 2026-04-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skill_unique_skill_name_case_insensitive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='skill',
            name='unique_skill_name_case_insensitive',
        ),
    ]
